#PDP Config

pdp_decode_current: "/safety/current"
pdp_decode_energy: "/safety/energy"

#List of CAN devices and their associated topics
#Essentially a dictionary.
#As we are using a lot of FRC devices, we will split them up by using the FRC address format. Devices
#are identified using the first 13 bits.
#Format: "CAN Device ID", "Device Type"
#Please see the documentation for more detail

#If you are wondering why the ID is a string and not an integer, it's because ROS maps only supports strings as keys :> 
#CAN Device types
#Uncomment this if running pdp_decode standalone
#can_device_types: {"0x804": "pdp"}


